apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend
  description: core o&m
  tags:
    - java
  links:
    - url: http://pizza
      title: Grafana dashboard
      icon: dashboard
    - url: http://pizza
      title: Staging logs
      icon: log
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
  annotations:
    qameta.io/allure-project: pizza
    github.com/project-slug: alorenzoni-boom/testdue
    github.com/manifest-file: project-version
    boom/drone-project: testdue
spec:
  type: service
  lifecycle: production
  owner: Team-OMS
  system: OM
  dependsOn: ['resource:artists-db']
  providesApis: ['backend']
