apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monetization-service
  description: core o&m
  tags:
    - java
  links:
    - url: http://pizza
      title: Grafana dashboard
      icon: dashboard
    - url: http://pizza
      title: Staging logs
      icon: log
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
  annotations:
    backstage.io/source-location: url:https://github.com/boom-image-studio/monetization-service
    github.com/project-slug: boom-image-studio/monetization-service
    github.com/manifest-file: pom.xml
    boom/drone-project: monetization-service
    boom/allure-project: backend
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=monetization-service'
    prometheus.io/rule: jvm:total_memory_used:total{service="monetization-service"}
spec:
  type: service
  lifecycle: production
  owner: Team-OMS
  system: OM
